require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Listing = require('../models/Listing');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://staynest_user:staynest_pass@localhost:27017/staynest?authSource=staynest';

const listings = [
  { title: "Cozy Beachfront Cottage", location: "Malibu", country: "United States", price: 1500, category: "Beach", image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=60", description: "Wake up to the sound of waves in this charming beachfront cottage.", rating: 4.9, reviews: 124, guests: 4, bedrooms: 2, bathrooms: 1, amenities: ["WiFi", "Beach Access", "Kitchen", "Parking"], host: { name: "Sarah M.", avatar: "https://i.pravatar.cc/100?img=1", joined: "2018" } },
  { title: "Modern Loft in Downtown", location: "New York City", country: "United States", price: 1200, category: "Iconic Cities", image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=60", description: "Stylish loft in the heart of NYC with stunning skyline views.", rating: 4.7, reviews: 89, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["WiFi", "Gym", "Doorman", "City View"], host: { name: "James K.", avatar: "https://i.pravatar.cc/100?img=2", joined: "2019" } },
  { title: "Mountain Retreat", location: "Aspen", country: "United States", price: 1000, category: "Mountains", image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=60", description: "Escape to the mountains in this cozy alpine retreat.", rating: 4.8, reviews: 67, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ["WiFi", "Fireplace", "Hot Tub", "Ski Storage"], host: { name: "Laura T.", avatar: "https://i.pravatar.cc/100?img=3", joined: "2017" } },
  { title: "Historic Villa in Tuscany", location: "Florence", country: "Italy", price: 2500, category: "Amazing Views", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=60", description: "A stunning 16th-century villa surrounded by rolling Tuscan hills.", rating: 5.0, reviews: 203, guests: 10, bedrooms: 5, bathrooms: 4, amenities: ["Pool", "Wine Cellar", "Garden", "Chef Service"], host: { name: "Marco R.", avatar: "https://i.pravatar.cc/100?img=4", joined: "2016" } },
  { title: "Secluded Treehouse Getaway", location: "Portland", country: "United States", price: 800, category: "Trending", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=60", description: "Unique treehouse experience nestled in the Pacific Northwest forest.", rating: 4.9, reviews: 156, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["WiFi", "Hammock", "Outdoor Shower", "Fire Pit"], host: { name: "Emma W.", avatar: "https://i.pravatar.cc/100?img=5", joined: "2020" } },
  { title: "Beachfront Paradise", location: "Cancun", country: "Mexico", price: 2000, category: "Beach", image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=60", description: "Crystal-clear waters and white sand beaches await you.", rating: 4.8, reviews: 178, guests: 8, bedrooms: 4, bathrooms: 3, amenities: ["Pool", "Beach Access", "Bar", "WiFi"], host: { name: "Carlos V.", avatar: "https://i.pravatar.cc/100?img=6", joined: "2018" } },
  { title: "Rustic Cabin by the Lake", location: "Lake Tahoe", country: "United States", price: 900, category: "Lake", image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60", description: "Peaceful lakeside cabin perfect for fishing and stargazing.", rating: 4.7, reviews: 94, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ["Kayaks", "Fireplace", "Boat Dock", "BBQ"], host: { name: "Mike H.", avatar: "https://i.pravatar.cc/100?img=7", joined: "2019" } },
  { title: "Luxury Penthouse with City Views", location: "Los Angeles", country: "United States", price: 3500, category: "Luxury", image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?w=800&q=60", description: "Top-floor penthouse with panoramic LA views and rooftop pool.", rating: 4.9, reviews: 112, guests: 4, bedrooms: 2, bathrooms: 2, amenities: ["Rooftop Pool", "Concierge", "Valet", "Home Theater"], host: { name: "Ashley G.", avatar: "https://i.pravatar.cc/100?img=8", joined: "2017" } },
  { title: "Ski-In/Ski-Out Chalet", location: "Verbier", country: "Switzerland", price: 3000, category: "Mountains", image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=800&q=60", description: "Ski directly from your door in the Swiss Alps.", rating: 4.9, reviews: 87, guests: 8, bedrooms: 4, bathrooms: 3, amenities: ["Ski Rental", "Sauna", "Fireplace", "Mountain View"], host: { name: "Hans B.", avatar: "https://i.pravatar.cc/100?img=9", joined: "2016" } },
  { title: "Safari Lodge in the Serengeti", location: "Serengeti National Park", country: "Tanzania", price: 4000, category: "Trending", image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=60", description: "Experience the wild from a luxury tented safari lodge.", rating: 5.0, reviews: 241, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["Safari Tours", "Butler", "Sundowner", "Wildlife Viewing"], host: { name: "Amara N.", avatar: "https://i.pravatar.cc/100?img=10", joined: "2015" } },
  { title: "Historic Canal House", location: "Amsterdam", country: "Netherlands", price: 1800, category: "Iconic Cities", image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=60", description: "Charming 17th-century canal house in the heart of Amsterdam.", rating: 4.8, reviews: 132, guests: 4, bedrooms: 2, bathrooms: 1, amenities: ["WiFi", "Bikes", "Canal View", "Breakfast"], host: { name: "Lena V.", avatar: "https://i.pravatar.cc/100?img=11", joined: "2018" } },
  { title: "Private Island Retreat", location: "Fiji", country: "Fiji", price: 10000, category: "Luxury", image: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?w=800&q=60", description: "Your own private island paradise in the South Pacific.", rating: 5.0, reviews: 58, guests: 12, bedrooms: 6, bathrooms: 6, amenities: ["Private Beach", "Yacht", "Dive Gear", "Chef"], host: { name: "Ratu S.", avatar: "https://i.pravatar.cc/100?img=12", joined: "2014" } },
  { title: "Charming Cottage in the Cotswolds", location: "Cotswolds", country: "United Kingdom", price: 1200, category: "Rooms", image: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800&q=60", description: "Quintessential English countryside charm with honey-stone walls.", rating: 4.8, reviews: 99, guests: 4, bedrooms: 2, bathrooms: 1, amenities: ["Garden", "Fireplace", "WiFi", "Parking"], host: { name: "Olivia B.", avatar: "https://i.pravatar.cc/100?img=13", joined: "2019" } },
  { title: "Historic Brownstone in Boston", location: "Boston", country: "United States", price: 2200, category: "Iconic Cities", image: "https://images.unsplash.com/photo-1533619239233-6280475a633a?w=800&q=60", description: "Classic Boston brownstone in the prestigious Beacon Hill neighborhood.", rating: 4.7, reviews: 76, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ["WiFi", "Laundry", "Parking", "City View"], host: { name: "Tom F.", avatar: "https://i.pravatar.cc/100?img=14", joined: "2018" } },
  { title: "Beachfront Bungalow in Bali", location: "Bali", country: "Indonesia", price: 1800, category: "Beach", image: "https://images.unsplash.com/photo-1602391833977-358a52198938?w=800&q=60", description: "Serene Balinese bungalow steps from the Indian Ocean.", rating: 4.9, reviews: 187, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["Private Pool", "Yoga Deck", "Rice Field View", "Breakfast"], host: { name: "Wayan S.", avatar: "https://i.pravatar.cc/100?img=15", joined: "2017" } },
  { title: "Mountain View Cabin in Banff", location: "Banff", country: "Canada", price: 1500, category: "Mountains", image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?w=800&q=60", description: "Stunning Rocky Mountain views from this cozy Canadian cabin.", rating: 4.8, reviews: 143, guests: 4, bedrooms: 2, bathrooms: 1, amenities: ["Hot Tub", "Hiking Trails", "Wildlife", "Firepit"], host: { name: "Claire D.", avatar: "https://i.pravatar.cc/100?img=16", joined: "2018" } },
  { title: "Art Deco Apartment in Miami", location: "Miami", country: "United States", price: 1600, category: "Iconic Cities", image: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?w=800&q=60", description: "Vibrant South Beach Art Deco apartment just steps from the ocean.", rating: 4.6, reviews: 88, guests: 4, bedrooms: 2, bathrooms: 2, amenities: ["Pool", "Beach Access", "WiFi", "Gym"], host: { name: "Diana R.", avatar: "https://i.pravatar.cc/100?img=17", joined: "2019" } },
  { title: "Tropical Villa in Phuket", location: "Phuket", country: "Thailand", price: 3000, category: "Luxury", image: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?w=800&q=60", description: "Lush tropical villa with infinity pool overlooking the Andaman Sea.", rating: 4.9, reviews: 165, guests: 8, bedrooms: 4, bathrooms: 4, amenities: ["Infinity Pool", "Chef", "Longtail Boat", "Spa"], host: { name: "Pim C.", avatar: "https://i.pravatar.cc/100?img=18", joined: "2016" } },
  { title: "Historic Castle in Scotland", location: "Scottish Highlands", country: "United Kingdom", price: 4000, category: "Castles", image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?w=800&q=60", description: "Sleep like royalty in a genuine 12th-century Scottish castle.", rating: 4.9, reviews: 201, guests: 16, bedrooms: 8, bathrooms: 6, amenities: ["Banquet Hall", "Archery", "Whisky Tasting", "Highland Tours"], host: { name: "Angus M.", avatar: "https://i.pravatar.cc/100?img=19", joined: "2015" } },
  { title: "Desert Oasis in Dubai", location: "Dubai", country: "United Arab Emirates", price: 5000, category: "Luxury", image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=60", description: "Ultra-luxury desert villa with private dunes and butler service.", rating: 5.0, reviews: 79, guests: 6, bedrooms: 3, bathrooms: 3, amenities: ["Private Pool", "Butler", "Dune Buggy", "Camel Ride"], host: { name: "Khalid A.", avatar: "https://i.pravatar.cc/100?img=20", joined: "2016" } },
  { title: "Rustic Log Cabin in Montana", location: "Montana", country: "United States", price: 1100, category: "Camping", image: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=800&q=60", description: "Off-grid log cabin in the wilderness of Big Sky Country.", rating: 4.7, reviews: 112, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ["Fireplace", "Fly Fishing", "Stargazing", "ATV Trails"], host: { name: "Buck T.", avatar: "https://i.pravatar.cc/100?img=21", joined: "2018" } },
  { title: "Beachfront Villa in Greece", location: "Mykonos", country: "Greece", price: 2500, category: "Beach", image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=60", description: "Iconic white-washed Cycladic villa overlooking the Aegean Sea.", rating: 4.9, reviews: 193, guests: 6, bedrooms: 3, bathrooms: 3, amenities: ["Private Pool", "Sea View", "Outdoor Kitchen", "Boat Charter"], host: { name: "Nikos P.", avatar: "https://i.pravatar.cc/100?img=22", joined: "2017" } },
  { title: "Eco-Friendly Treehouse Retreat", location: "Costa Rica", country: "Costa Rica", price: 750, category: "Trending", image: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?w=800&q=60", description: "Sustainable treehouse immersed in lush rainforest canopy.", rating: 4.8, reviews: 147, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["Hammock", "Solar Power", "Wildlife", "Canopy Tour"], host: { name: "Daniela Q.", avatar: "https://i.pravatar.cc/100?img=23", joined: "2019" } },
  { title: "Historic Cottage in Charleston", location: "Charleston", country: "United States", price: 1600, category: "Rooms", image: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=800&q=60", description: "Antebellum charm in one of America's most beautiful historic cities.", rating: 4.8, reviews: 108, guests: 4, bedrooms: 2, bathrooms: 2, amenities: ["Porch Swing", "Garden", "WiFi", "Bikes"], host: { name: "Grace L.", avatar: "https://i.pravatar.cc/100?img=24", joined: "2018" } },
  { title: "Modern Apartment in Tokyo", location: "Tokyo", country: "Japan", price: 2000, category: "Iconic Cities", image: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800&q=60", description: "Sleek Tokyo apartment in the heart of Shinjuku district.", rating: 4.7, reviews: 134, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["WiFi", "Capsule Bed", "High-Tech Toilet", "Transit Pass"], host: { name: "Yuki T.", avatar: "https://i.pravatar.cc/100?img=25", joined: "2019" } },
  { title: "Lakefront Cabin in New Hampshire", location: "New Hampshire", country: "United States", price: 1200, category: "Lake", image: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?w=800&q=60", description: "Classic New England lakefront cabin with dock and canoes.", rating: 4.7, reviews: 91, guests: 8, bedrooms: 4, bathrooms: 2, amenities: ["Canoes", "Fishing", "Fire Pit", "Screened Porch"], host: { name: "Randy K.", avatar: "https://i.pravatar.cc/100?img=26", joined: "2018" } },
  { title: "Luxury Villa in the Maldives", location: "Maldives", country: "Maldives", price: 6000, category: "Luxury", image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=60", description: "Overwater villa with glass floor and direct ocean access.", rating: 5.0, reviews: 312, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["Glass Floor", "Snorkeling", "Spa", "Underwater Restaurant"], host: { name: "Ibrahim D.", avatar: "https://i.pravatar.cc/100?img=27", joined: "2015" } },
  { title: "Organic Farm Stay in Tuscany", location: "Siena", country: "Italy", price: 950, category: "Farms", image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=60", description: "Stay on a working organic farm in the heart of Tuscany.", rating: 4.8, reviews: 78, guests: 4, bedrooms: 2, bathrooms: 1, amenities: ["Farm Tours", "Cooking Class", "Wine Tasting", "Pool"], host: { name: "Francesca B.", avatar: "https://i.pravatar.cc/100?img=28", joined: "2018" } },
  { title: "Medieval Castle in Loire Valley", location: "Loire Valley", country: "France", price: 3200, category: "Castles", image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=60", description: "Magnificent Renaissance château in France's garden of castles.", rating: 4.9, reviews: 87, guests: 12, bedrooms: 6, bathrooms: 5, amenities: ["Moat", "Banquet Hall", "Wine Cellar", "Horse Riding"], host: { name: "Pierre L.", avatar: "https://i.pravatar.cc/100?img=29", joined: "2016" } },
  { title: "Glamping Dome in New Zealand", location: "Queenstown", country: "New Zealand", price: 600, category: "Camping", image: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&q=60", description: "Transparent geodesic dome under the Southern Hemisphere stars.", rating: 4.9, reviews: 162, guests: 2, bedrooms: 1, bathrooms: 1, amenities: ["Stargazing", "Bungee Access", "Breakfast", "Thermal Blankets"], host: { name: "Kiri W.", avatar: "https://i.pravatar.cc/100?img=30", joined: "2019" } }
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');
    await Listing.deleteMany({});
    console.log('🗑️  Cleared existing listings');
    const created = await Listing.insertMany(listings);
    console.log(`🌱 Seeded ${created.length} listings successfully`);
    await mongoose.disconnect();
    console.log('✅ Done! MongoDB disconnected.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
}

seed();
